name: "PR checks"

on:
  push:
    paths:
      - 'edit_here_to_add_blocklists.json'
      - '.github/**'
      - 'tests/**'
      - '**.sh'
  pull_request:   
  schedule:
    - cron: "6 6 * * *"
  workflow_dispatch:


jobs:
  Checks:
    name: "Running checks"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get install -y --no-install-recommends ca-certificates curl git jq
      - name: "Checkout project"
        uses: "actions/checkout@v3.2.0"
    
      - name: "Checking file names"
        run: |
          bash tests/fileName.sh
    
      - name: "Checking values"
        run: |
          bash tests/value.sh
    
      - name: "Checking URLs"
        run: |
          bash tests/url.sh
    
