name: "Generate regex test data"

on:
  push:
    paths:
      - "download.js"
      - "test_data/input.txt"

  workflow_dispatch:

jobs:
  Checks:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.0
      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "19"

      - name: "Install node dependencies"
        run: |
          npm install

      - name: "Getting new file"
        run: |
          npm run genRegex

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: "DW [github actions bot]"
          message: "updated to new regex test file [skip ci]"
