name: "List updates"

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'tests/**'
      - 'custom_filters/wildcard/**'
      - 'custom_filters/normal/**'

  schedule:
    - cron: "6 6 * * *"
  workflow_dispatch:



jobs:
  update:
    name: "Update"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get install -y --no-install-recommends ca-certificates curl git jq
      - name: "Checkout project"
        uses: "actions/checkout@v3.2.0"
      - name: "Update lists"
        run: |
          bash update.sh
      - name: "Build json"
        run: |
          bash buildJson.sh


      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: 'DW [github actions bot]'
          message: 'auto-update [skip ci]'
          
          
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ secrets.REPO_NAME }}
          event-type: start-building
          
